export const CONTENT_CATEGORIES = {
  originals: {
    id: 'originals',
    title: 'Originals',
    desc: 'Feature films & web series blending cinematic entertainment with sustainability and future innovation.',
    color: 'from-violet-500 to-indigo-600',
    glow: 'shadow-indigo-500/25',
    accent: 'text-indigo-400',
    bg: 'bg-indigo-500/10',
    border: 'border-indigo-500/20',
    items: [
      {
        title: 'Neural Nation',
        type: 'Web Series',
        year: '2025',
        duration: '6 ep',
        tagline: 'AI reshaping every industry',
        category: 'Artificial Intelligence',
        desc: 'A deep dive into how neural networks and intelligent agents are revolutionizing Indian industry, healthcare, and creative processes.',
        gradientIdx: 0,
        youtubeId: 'OVs2HB9CWZE',
        director: 'Snehasis Medda',
        location: 'Bengaluru & Hyderabad, India',
        experts: ['Dr. Priya Sen (AI Ethics)', 'Aniket Roy (Tech Investor)'],
        greenFilming: 'Set operated entirely on reusable battery arrays; zero paper footprint.'
      },
      {
        title: 'City Brain',
        type: 'Docuseries',
        year: '2025',
        duration: '4 ep',
        tagline: 'When cities start thinking',
        category: 'Smart Cities',
        desc: 'An exploration of next-generation urban operating systems, IoT sensor networks, and real-time traffic automation in India\'s rising smart cities.',
        gradientIdx: 6,
        youtubeId: 'xdZiUuwZeOI',
        director: 'Aniket Bose',
        location: 'Command Center, Pune, India',
        experts: ['Suresh Kumar (IoT Engineer)', 'Meera Nair (Urban Planner)'],
        greenFilming: 'Hybrid shuttle transport used for crew transit; 100% LED production lights.'
      },
      {
        title: 'Electric India',
        type: 'Web Series',
        year: '2024',
        duration: '8 ep',
        tagline: 'The race to electrify a nation',
        category: 'Electric Mobility',
        desc: 'Following the visionary startups and policymakers building India\'s EV charging infrastructure, battery tech, and electric grids.',
        gradientIdx: 2,
        youtubeId: '9udS0mpi1L4',
        director: 'Rohan Sharma',
        location: 'Tamil Nadu & Delhi NCR, India',
        experts: ['Amit Verma (EV Battery Tech)', 'Vikas Gowda (Policy Researcher)'],
        greenFilming: 'Set powered 100% by portable solar generators; zero single-use plastic.'
      },
      {
        title: 'The Inventor',
        type: 'Feature Film',
        year: '2026',
        duration: '112 min',
        tagline: 'Inside the mind of India\'s Edison',
        category: 'Innovation',
        desc: 'A biographical drama tracking the trials and triumphs of a rural inventor whose low-cost wind generator changed lives.',
        gradientIdx: 3,
        youtubeId: 'scVjgI2p02M',
        director: 'Medha Sen',
        location: 'Satara, Maharashtra, India',
        experts: ['Dilip Patil (Wind Turbine Innovator)', 'Dr. Rajesh Deshmukh'],
        greenFilming: 'Green shoot certification; local organic catering on set.'
      },
      {
        title: 'Deep Blue',
        type: 'Docuseries',
        year: '2025',
        duration: '5 ep',
        tagline: 'Exploring the Indian Ocean\'s depths',
        category: 'Ocean Science',
        desc: 'An immersive cinematic journey profiling oceanographers studying climate impacts and deep-sea biodiversity.',
        gradientIdx: 5,
        youtubeId: 'rGNc8RRggzo',
        director: 'Snehasis Medda',
        location: 'Indian Ocean (Offshore, India)',
        experts: ['Dr. Radhika Roy (Oceanographer)', 'Capt. Sunil Dutt'],
        greenFilming: 'Low-emission research vessel utilized; zero marine waste guidelines enforced.'
      }
    ]
  },
  documentaries: {
    id: 'documentaries',
    title: 'Documentaries',
    desc: 'Rigorous, visually stunning non-fiction covering the technologies and ideas driving tomorrow.',
    color: 'from-emerald-500 to-teal-600',
    glow: 'shadow-emerald-500/25',
    accent: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    items: [
      {
        title: 'Zero Mile',
        type: 'Documentary',
        year: '2024',
        duration: '58 min',
        tagline: 'The race to electrify India',
        category: 'Electric Mobility',
        desc: 'Behind the scenes of India\'s monumental shift to clean transit, from battery gigafactories to electric two-wheelers.',
        gradientIdx: 1,
        youtubeId: 'rGNc8RRggzo',
        director: 'Vikram Aditya',
        location: 'Nagpur Gigafactory, India',
        experts: ['Arun Joshi (Gigafactory Lead)', 'Dr. Sarla Devi'],
        greenFilming: '100% solar charging on set; electric fleet vehicle transit.'
      },
      {
        title: 'Solar Surge',
        type: 'Documentary',
        year: '2024',
        duration: '72 min',
        tagline: 'How sunlight became power',
        category: 'Renewable Energy',
        desc: 'Inside the mega solar parks of Rajasthan and Gujarat, highlighting the engineers and communities powering the future.',
        gradientIdx: 7,
        youtubeId: '2Vv-BfVoq4g',
        director: 'Nehal Shah',
        location: 'Bhadla Solar Park, Rajasthan, India',
        experts: ['Rajesh Singhal (Solar Engineer)', 'Sanjana Sen'],
        greenFilming: 'Off-grid filming set powered by a custom solar trailer generator.'
      },
      {
        title: 'Orbit India',
        type: 'Documentary',
        year: '2025',
        duration: '90 min',
        tagline: 'ISRO\'s next giant leap',
        category: 'Space Exploration',
        desc: 'An exclusive inside look at the planning, engineering, and human stories behind India\'s upcoming human spaceflight mission.',
        gradientIdx: 2,
        youtubeId: 'f632N7wG98k',
        director: 'Karan Roy',
        location: 'Sriharikota Space Center, India',
        experts: ['Dr. Madhavan Nair (ISRO Scientist)', 'Dr. Sunita Rao'],
        greenFilming: 'Low-carbon footprint travel and remote virtual production sets.'
      },
      {
        title: 'The Code of Life',
        type: 'Documentary',
        year: '2025',
        duration: '64 min',
        tagline: 'Rewriting biology itself',
        category: 'Biotechnology',
        desc: 'Exploring the biotech revolution in agriculture, gene editing, and medical therapeutics across research labs in Bangalore.',
        gradientIdx: 5,
        youtubeId: 'wYp_l_c4uI0',
        director: 'Alok Sen',
        location: 'IISc Bangalore labs, India',
        experts: ['Dr. Priya Kurien (Geneticist)', 'Dr. Shridhar Bhat'],
        greenFilming: 'Lab-safe green production techniques.'
      },
      {
        title: 'The Battery Race',
        type: 'Documentary',
        year: '2024',
        duration: '52 min',
        tagline: 'Inside the EV supply chain',
        category: 'Electric Mobility',
        desc: 'A global investigation into the critical mineral supply chain, lithium sourcing, and local recycling innovations.',
        gradientIdx: 8,
        youtubeId: 'scVjgI2p02M',
        director: 'Snehasis Medda',
        location: 'Dhanbad & Mumbai, India',
        experts: ['Kunal Sen (Mineralogist)', 'Anita Desai (EV Recycler)'],
        greenFilming: 'Zero-waste sets; compostable catering packaging.'
      }
    ]
  },
  impact: {
    id: 'impact',
    title: 'Impact Films',
    desc: 'Purpose-driven stories engineered to inspire behavioural shift, awareness, and positive change.',
    color: 'from-amber-500 to-orange-600',
    glow: 'shadow-amber-500/25',
    accent: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/20',
    items: [
      {
        title: 'Carbon Zero',
        type: 'Impact Film',
        year: '2024',
        duration: '45 min',
        tagline: 'Building a net-zero future',
        category: 'Climate Resilience',
        desc: 'Profiling heavy industries and startups collaborating to eliminate carbon emissions in steel and cement manufacturing.',
        gradientIdx: 4,
        youtubeId: 'scVjgI2p02M',
        director: 'Preeti Vyas',
        location: 'Jamshedpur Steel Plant, India',
        experts: ['R. P. Sinha (Green Steel Expert)', 'Dr. T. K. Rao'],
        greenFilming: 'Eco-set certification; carbon offsetting for crew flights.'
      },
      {
        title: 'Wind Harvest',
        type: 'Impact Film',
        year: '2024',
        duration: '38 min',
        tagline: 'Coastal wind power pioneers',
        category: 'Renewable Energy',
        desc: 'The stories of local communities in Tamil Nadu living alongside some of the world\'s largest onshore wind farms.',
        gradientIdx: 7,
        youtubeId: 'dQw4w9WgXcQ',
        director: 'Gaurav Das',
        location: 'Kanyakumari Coast, India',
        experts: ['M. K. Pandian (Wind Engineer)', 'Dr. Devika'],
        greenFilming: 'Filming rigs powered by locally sourced wind battery storage.'
      },
      {
        title: 'Clean Air Delhi',
        type: 'Impact Film',
        year: '2025',
        duration: '30 min',
        tagline: 'The fight for blue skies',
        category: 'Climate Resilience',
        desc: 'A hard-hitting visual study of Delhi\'s air quality initiatives, community activism, and policy battles.',
        gradientIdx: 8,
        youtubeId: 'xP_98g7n27s',
        director: 'Rahul Verma',
        location: 'New Delhi, India',
        experts: ['Dr. Anita Roy (Pulmonologist)', 'Sunil Sharma'],
        greenFilming: 'Filming crew utilized public electric buses for transportation.'
      },
      {
        title: 'Mission Green',
        type: 'Impact Film',
        year: '2024',
        duration: '40 min',
        tagline: 'India\'s afforestation movement',
        category: 'Climate Resilience',
        desc: 'Witness the efforts of micro-forest creators restoring local ecosystems using Miyawaki planting methods.',
        gradientIdx: 1,
        youtubeId: 'dQw4w9WgXcQ',
        director: 'Siddharth Roy',
        location: 'Western Ghats, India',
        experts: ['J. P. Mathew (Forest Ecologist)', 'V. Kurian'],
        greenFilming: 'Crew planted 100 native saplings to offset filming footprint.'
      },
      {
        title: 'Water Stories',
        type: 'Impact Film',
        year: '2025',
        duration: '35 min',
        tagline: 'Reviving ancient water bodies',
        category: 'Climate Resilience',
        desc: 'How citizen-led groups in Bangalore and Chennai are leveraging IoT and traditional wisdom to save local lakes.',
        gradientIdx: 6,
        youtubeId: 'v64KOxKVzXM',
        director: 'Snehasis Medda',
        location: 'Bangalore Lakes, India',
        experts: ['S. Vishwanath (Water Expert)', 'Dr. Asha Sen'],
        greenFilming: 'Biodegradable crew supplies; zero local water body disruption.'
      }
    ]
  },
  learning: {
    id: 'learning',
    title: 'Learning Content',
    desc: 'Educational content making complex science, tech, and engineering accessible and engaging.',
    color: 'from-sky-500 to-blue-600',
    glow: 'shadow-sky-500/25',
    accent: 'text-sky-400',
    bg: 'bg-sky-500/10',
    border: 'border-sky-500/20',
    items: [
      {
        title: 'EV Tech 101',
        type: 'Educational',
        year: '2024',
        duration: '15 min',
        tagline: 'How electric drivetrains work',
        category: 'Electric Mobility',
        desc: 'An animated guide breaking down batteries, motor controllers, regenerative braking, and thermal management.',
        gradientIdx: 6,
        youtubeId: 'scVjgI2p02M',
        director: 'Aniket Bose',
        location: 'Vellore Tech Center, India',
        experts: ['Dr. K. Balaji (EV Professor)'],
        greenFilming: 'Volumetric virtual studio set; zero physical material waste.'
      },
      {
        title: 'ISRO Science Series',
        type: 'Educational',
        year: '2025',
        duration: '25 min',
        tagline: 'The physics of rocket launches',
        category: 'Space Exploration',
        desc: 'A visually rich explainer series detailing orbital mechanics, cryogenic propulsion, and satellite deployment.',
        gradientIdx: 3,
        youtubeId: 'f632N7wG98k',
        director: 'Aditya Varma',
        location: 'ISRO Exhibition Hall, India',
        experts: ['Dr. R. Ramanathan (Aerospace Engineer)'],
        greenFilming: 'Volumetric digital assets used; paperless production scripts.'
      },
      {
        title: 'IIT Research Profiles',
        type: 'Educational',
        year: '2025',
        duration: '20 min',
        tagline: 'Next-gen innovations',
        category: 'Human Achievement',
        desc: 'Highlighting cutting-edge research projects from the Indian Institutes of Technology in AI, materials science, and robotics.',
        gradientIdx: 0,
        youtubeId: 'dQw4w9WgXcQ',
        director: 'Sonal Sen',
        location: 'IIT Bombay Campus, India',
        experts: ['Prof. Amitava Ghosh', 'Dr. Radhika Pillai'],
        greenFilming: 'LED studio lights; digital catering plans.'
      },
      {
        title: 'Solar Physics',
        type: 'Educational',
        year: '2024',
        duration: '18 min',
        tagline: 'Harnessing fusion at scale',
        category: 'Renewable Energy',
        desc: 'The science behind photovoltaic cells, energy storage, and smart grid synchronization.',
        gradientIdx: 1,
        youtubeId: '921VbEMAUtY',
        director: 'Nehal Shah',
        location: 'IIT Madras Campus, India',
        experts: ['Dr. H. S. Murthy (Physics Head)'],
        greenFilming: 'Set operated on 100% solar panels.'
      },
      {
        title: 'Deep Learning',
        type: 'Educational',
        year: '2025',
        duration: '22 min',
        tagline: 'Neural networks explained visually',
        category: 'Artificial Intelligence',
        desc: 'An intuitive graphical walkthrough of backpropagation, convolutional networks, and transformer models.',
        gradientIdx: 2,
        youtubeId: 'wYp_l_c4uI0',
        director: 'Dr. Alok Sen',
        location: 'IISc Data Labs, Bangalore, India',
        experts: ['Prof. Ramesh Bhat (ML Chair)'],
        greenFilming: 'Volumetric virtual studio set.'
      }
    ]
  },
  futurelab: {
    id: 'futurelab',
    title: 'FutureLab',
    desc: 'Experimental and cutting-edge media exploring AI-generated storytelling, volumetric, and immersive interactive tech.',
    color: 'from-pink-500 to-rose-600',
    glow: 'shadow-pink-500/25',
    accent: 'text-pink-400',
    bg: 'bg-pink-500/10',
    border: 'border-pink-500/20',
    items: [
      {
        title: 'VR: Inside the Sun',
        type: 'Experimental',
        year: '2024',
        duration: '10 min',
        tagline: 'A 360° virtual reality journey',
        category: 'Space Exploration',
        desc: 'An interactive virtual reality simulation of solar wind, solar flares, and the corona.',
        gradientIdx: 4,
        youtubeId: 'scVjgI2p02M',
        director: 'Vikram Aditya',
        location: 'Virtual Production Studio, India',
        experts: ['Dr. Vikram Sarabhai Roy'],
        greenFilming: 'Virtual set production, zero physical material waste.'
      },
      {
        title: 'AI Shorts Lab',
        type: 'Experimental',
        year: '2025',
        duration: '12 min',
        tagline: 'Exploring generative cinema',
        category: 'Artificial Intelligence',
        desc: 'A collection of cinematic short films co-created with state-of-the-art generative video models.',
        gradientIdx: 5,
        youtubeId: '5dVM8H3fV2w',
        director: 'Snehasis Medda',
        location: 'Generative AI Studio, India',
        experts: ['Meera Bose (Generative Artist)'],
        greenFilming: '100% digital pipeline; zero-carbon cloud servers utilized.'
      },
      {
        title: 'Holo-Docs',
        type: 'Experimental',
        year: '2025',
        duration: '15 min',
        tagline: 'Holographic documentary experiences',
        category: 'Innovation',
        desc: 'Prototype narratives engineered for volumetric displays and mixed reality headsets.',
        gradientIdx: 3,
        youtubeId: 'dQw4w9WgXcQ',
        director: 'Aniket Bose',
        location: 'Holographic Lab, Bengaluru, India',
        experts: ['Prof. Shreedhar Nair'],
        greenFilming: 'Volumetric capture technology with zero carbon props.'
      },
      {
        title: 'Quantum Cinema',
        type: 'Experimental',
        year: '2026',
        duration: '14 min',
        tagline: 'Narratives based on quantum mechanics',
        category: 'Innovation',
        desc: 'An experimental narrative film where viewer choices collapse superposition states to alter the plot.',
        gradientIdx: 0,
        youtubeId: 'dQw4w9WgXcQ',
        director: 'Rohan Sharma',
        location: 'Quantum Computing Center, India',
        experts: ['Dr. Priya Kurien'],
        greenFilming: 'Zero-waste sets; compostable materials.'
      },
      {
        title: 'Cyber-Forest',
        type: 'Experimental',
        year: '2025',
        duration: '18 min',
        tagline: 'An interactive digital biosphere',
        category: 'Climate Resilience',
        desc: 'A real-time 3D simulation of a forest ecosystem reacting dynamically to global environmental datasets.',
        gradientIdx: 7,
        youtubeId: 'v64KOxKVzXM',
        director: 'Siddharth Roy',
        location: 'Generative AI Studio, India',
        experts: ['J. P. Mathew (Forest Ecologist)'],
        greenFilming: '100% digital pipeline; zero carbon servers.'
      }
    ]
  }
};
